Update LTS and use githash instead of gitrev
fpco/optparse-simple pull request #10
Opened 2018-12-24 05:10 UTC by waddlaw

2018-12-24 11:43 UTC, snoyberg requested changes
Looks great, thanks! Just one minor request around the `"UNKNOWN"` bit.

2018-12-24 11:43 UTC, snoyberg commented on package.yaml
> +- base >= 4.9.1 && <5
Wow, you nailed the changelog, Travis, and hpack file changes. Color me impressed!

2018-12-24 11:43 UTC, snoyberg commented on src/Options/Applicative/Simple.hs
> +               if giHash gi == "UNKNOWN"
I _think_ this should be unnecessary now, since `gi` itself will do all error checking and return a `Left` if relevant.

2018-12-24 15:28 UTC, waddlaw commented
@snoyberg this should be all set now :) Is this alright?

- remove unnecessary condition
- add simple example

example result:

```shell
$ stack run
Version 0.1.1, Git revision b644835f1c7fbab207fe7976407b832ff2d17b50
```

2018-12-25 05:13 UTC, snoyberg approved these changes
Thanks!

2018-12-25 05:13 UTC, merged